# CS 3110/5110: Data Privacy

## In-Class Exercise, week of 8/31/2026

In [ ]:
# Load the data and libraries
import pandas as pd
import numpy as np

adult = pd.read_csv(
    "https://github.com/jnear/cs3110-data-privacy/raw/refs/heads/main/homework/adult_with_pii.csv"
)

## Question 1

Construct a de-identified version of the `adult` dataset.

In [2]:
print(adult.columns.tolist())

['Name', 'DOB', 'SSN', 'Zip', 'Age', 'Workclass', 'fnlwgt', 'Education', 'Education-Num', 'Marital Status', 'Occupation', 'Relationship', 'Race', 'Sex', 'Capital Gain', 'Capital Loss', 'Hours per week', 'Country', 'Target']

In [ ]:
def deidentify_adult():
    # YOUR CODE HERE
    raise NotImplementedError()


adult_deid = deidentify_adult()

In [ ]:
assert "Name" not in adult_deid.columns
assert "DOB" not in adult_deid.columns
assert "SSN" not in adult_deid.columns

## Question 2

What columns did you remove from the dataset to de-identify it? Why did you choose these columns? Why did you not choose the remaining columns?

I picked Name, DOB, and SSN.
There are many columns in the dataset that could identify someone, but we have to choose something. These three columns are nearly certain to uniquely identify someone, but it is just a judgement call. The exact options to pick are a grey area, there is no exact solution here. Name and SSN definitely do, and DOB might, so let's be safe and do all three.

How to decide? "Think hard and do your best."

## Question 3

Write a pandas expression to return just the row containing information about Brenn McNeely.

In [ ]:
type(adult["DOB"])
# row of just one person?
adult[
    "Name"
] == "Brenn McNeely"  # returns true for the row of Brenn McNeely, false for all other rows
adult[adult["Name"] == "Brenn McNeely"]  # returns the row of Brenn McNeely
# The pattern is dataFrame[condition]

,Name,DOB,SSN,Zip,Age,Workclass,fnlwgt,Education,Education-Num,Marital Status,Occupation,Relationship,Race,Sex,Capital Gain,Capital Loss,Hours per week,Country,Target
2,Brenn McNeely,8/6/1991,725-59-9860,95668,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K

In [ ]:
def get_brenns_row():
    return adult[adult["Name"] == "Brenn McNeely"]


brenns_row = get_brenns_row()[["Name", "DOB", "Zip", "Age"]]

In [ ]:
assert len(brenns_row) == 1
assert brenns_row["Zip"].iloc[0] == 95668
assert brenns_row["Age"].iloc[0] == 38

In [12]:
brenns_row

            Name       DOB    Zip  Age
2  Brenn McNeely  8/6/1991  95668   38

## Question 4

Conduct a linking attack to recover Brenn's data from the `adult_deid` dataset.

In [ ]:
# We have zip and age available, does this uniquely identify Brenn? Let's check:

In [ ]:
def recover_brenns_row():
    brenn_age = 38
    brenn_zip = 95668

    # NOTE: in pandas you need to use single &, not double &&. And you
    # need to put parentheses around each condition.
    return adult[(adult["Age"] == brenn_age) & (adult["Zip"] == brenn_zip)]


brenns_recovered_row = recover_brenns_row()

In [ ]:
assert len(brenns_recovered_row) == 1
assert brenns_recovered_row["Education"].iloc[0] == "HS-grad"